/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: .\daapi.i

#ifndef SWIG_daapi_WRAP_H_
#define SWIG_daapi_WRAP_H_

class Swig_memory;

class SwigDirector_IMarketEvent : public Directaccess::IMarketEvent
{
 public:
  SwigDirector_IMarketEvent(int swig_p);
  void _swig_upcall_OnFrontConnected() {
    Directaccess::IMarketEvent::OnFrontConnected();
  }
  virtual void OnFrontConnected();
  void _swig_upcall_OnFrontDisconnected(int iReason) {
    Directaccess::IMarketEvent::OnFrontDisconnected(iReason);
  }
  virtual void OnFrontDisconnected(int iReason);
  void _swig_upcall_OnHeartBeatWarning(int iTimeLapse) {
    Directaccess::IMarketEvent::OnHeartBeatWarning(iTimeLapse);
  }
  virtual void OnHeartBeatWarning(int iTimeLapse);
  void _swig_upcall_OnRspRawData(char const *rawData) {
    Directaccess::IMarketEvent::OnRspRawData(rawData);
  }
  virtual void OnRspRawData(char const *rawData);
  void _swig_upcall_OnRspUserLogin(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::IMarketEvent::OnRspUserLogin(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspUserLogin(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspTradeDate(CMarketRspTradeDateField *pRspTradeDate,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::IMarketEvent::OnRspTradeDate(pRspTradeDate,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspTradeDate(CMarketRspTradeDateField *pRspTradeDate,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspBrokerData(CMarketRspBrokerDataField *pRspBrokerData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::IMarketEvent::OnRspBrokerData(pRspBrokerData,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspBrokerData(CMarketRspBrokerDataField *pRspBrokerData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspMarketData(CMarketRspMarketDataField *pRspMarketData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::IMarketEvent::OnRspMarketData(pRspMarketData,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspMarketData(CMarketRspMarketDataField *pRspMarketData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspUserLogout(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::IMarketEvent::OnRspUserLogout(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspUserLogout(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnJsonData(CMarketRspJsonDataField *pRspMarketData) {
    Directaccess::IMarketEvent::OnJsonData(pRspMarketData);
  }
  virtual void OnJsonData(CMarketRspJsonDataField *pRspMarketData);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
