/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: .\daapi.i

#ifndef SWIG_daapi_WRAP_H_
#define SWIG_daapi_WRAP_H_

class Swig_memory;

class SwigDirector_IFutureEvent : public Directaccess::Directaccess::IFutureEvent
{
 public:
  SwigDirector_IFutureEvent(int swig_p);
  void _swig_upcall_OnFrontConnected() {
    Directaccess::Directaccess::IFutureEvent::OnFrontConnected();
  }
  virtual void OnFrontConnected();
  void _swig_upcall_OnFrontDisconnected(int iReason) {
    Directaccess::Directaccess::IFutureEvent::OnFrontDisconnected(iReason);
  }
  virtual void OnFrontDisconnected(int iReason);
  void _swig_upcall_OnHeartBeatWarning(int iTimeLapse) {
    Directaccess::Directaccess::IFutureEvent::OnHeartBeatWarning(iTimeLapse);
  }
  virtual void OnHeartBeatWarning(int iTimeLapse);
  void _swig_upcall_OnRspNeedVerify(bool bFirstLogin,bool bHasSetQA) {
    Directaccess::Directaccess::IFutureEvent::OnRspNeedVerify(bFirstLogin,bHasSetQA);
  }
  virtual void OnRspNeedVerify(bool bFirstLogin,bool bHasSetQA);
  void _swig_upcall_OnRspUserLogin(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspUserLogin(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspUserLogin(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspUserLogout(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspUserLogout(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspUserLogout(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspVerifyCode(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspVerifyCode(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspVerifyCode(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspSafeVerify(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspSafeVerify(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspSafeVerify(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspSetVerifyQA(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspSetVerifyQA(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspSetVerifyQA(CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspAccount(CFutureRspAccountField *pRspAccount,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspAccount(pRspAccount,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspAccount(CFutureRspAccountField *pRspAccount,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQuestion(CFutureRspQuestionField *pRspVersion,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQuestion(pRspVersion,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQuestion(CFutureRspQuestionField *pRspVersion,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspOrderInsert(CFutureRspOrderInsertField *pRspOrderInsert,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspOrderInsert(pRspOrderInsert,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspOrderInsert(CFutureRspOrderInsertField *pRspOrderInsert,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspOrderModify(CFutureRspOrderModifyField *pRspOrderModify,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspOrderModify(pRspOrderModify,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspOrderModify(CFutureRspOrderModifyField *pRspOrderModify,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspOrderCancel(CFutureRspOrderCancelField *pRspOrderCancel,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspOrderCancel(pRspOrderCancel,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspOrderCancel(CFutureRspOrderCancelField *pRspOrderCancel,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspPasswordUpdate(CFutureRspPasswordUpdateField *pRspPasswordUpdate,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspPasswordUpdate(pRspPasswordUpdate,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspPasswordUpdate(CFutureRspPasswordUpdateField *pRspPasswordUpdate,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRtnTrade(CFutureRtnTradeField *pRtnTrade,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRtnTrade(pRtnTrade,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRtnTrade(CFutureRtnTradeField *pRtnTrade,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRtnOrder(CFutureRtnOrderField *pRtnOrder,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRtnOrder(pRtnOrder,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRtnOrder(CFutureRtnOrderField *pRtnOrder,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRtnCapital(CFutureRtnCapitalField *pRtnCapital,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRtnCapital(pRtnCapital,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRtnCapital(CFutureRtnCapitalField *pRtnCapital,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRtnPosition(CFutureRtnPositionField *pRtnPosition,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRtnPosition(pRtnPosition,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRtnPosition(CFutureRtnPositionField *pRtnPosition,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryOrder(CFutureRspOrderField *pRspOrder,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryOrder(pRspOrder,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryOrder(CFutureRspOrderField *pRspOrder,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryTrade(CFutureRspTradeField *pRspTrade,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryTrade(pRspTrade,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryTrade(CFutureRspTradeField *pRspTrade,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryCapital(CFutureRspCapitalField *pRspCapital,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryCapital(pRspCapital,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryCapital(CFutureRspCapitalField *pRspCapital,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryVersion(CFutureRspVersionField *pRspVersion,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryVersion(pRspVersion,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryVersion(CFutureRspVersionField *pRspVersion,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryPosition(CFutureRspPositionField *pRspPosition,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryPosition(pRspPosition,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryPosition(CFutureRspPositionField *pRspPosition,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryCurrency(CFutureRspCurrencyField *pRspCurrency,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryCurrency(pRspCurrency,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryCurrency(CFutureRspCurrencyField *pRspCurrency,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryExchange(CFutureRspExchangeField *pRspExchange,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryExchange(pRspExchange,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryExchange(CFutureRspExchangeField *pRspExchange,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryStrategy(CFutureRspStrategyField *pRspStrategy,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryStrategy(pRspStrategy,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryStrategy(CFutureRspStrategyField *pRspStrategy,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryCommodity(CFutureRspCommodityField *pRspCommodity,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryCommodity(pRspCommodity,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryCommodity(CFutureRspCommodityField *pRspCommodity,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryInstrument(CFutureRspInstrumentField *pRspInstrument,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryInstrument(pRspInstrument,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryInstrument(CFutureRspInstrumentField *pRspInstrument,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryExchangeTime(CFutureRspExchangeTimeField *pRspExchangeTime,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryExchangeTime(pRspExchangeTime,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryExchangeTime(CFutureRspExchangeTimeField *pRspExchangeTime,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryCommodityTime(CFutureRspCommodityTimeField *pRspCommodityTime,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryCommodityTime(pRspCommodityTime,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryCommodityTime(CFutureRspCommodityTimeField *pRspCommodityTime,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryTotalPosition(CFutureRspTotalPositionField *pRspTotalPosition,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryTotalPosition(pRspTotalPosition,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryTotalPosition(CFutureRspTotalPositionField *pRspTotalPosition,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspQryStrategyDetail(CFutureRspStrategyDetailField *pRspStrategyDetail,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IFutureEvent::OnRspQryStrategyDetail(pRspStrategyDetail,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspQryStrategyDetail(CFutureRspStrategyDetailField *pRspStrategyDetail,CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

class SwigDirector_IMarketEvent : public Directaccess::Directaccess::IMarketEvent
{
 public:
  SwigDirector_IMarketEvent(int swig_p);
  void _swig_upcall_OnFrontConnected() {
    Directaccess::Directaccess::IMarketEvent::OnFrontConnected();
  }
  virtual void OnFrontConnected();
  void _swig_upcall_OnFrontDisconnected(int iReason) {
    Directaccess::Directaccess::IMarketEvent::OnFrontDisconnected(iReason);
  }
  virtual void OnFrontDisconnected(int iReason);
  void _swig_upcall_OnHeartBeatWarning(int iTimeLapse) {
    Directaccess::Directaccess::IMarketEvent::OnHeartBeatWarning(iTimeLapse);
  }
  virtual void OnHeartBeatWarning(int iTimeLapse);
  void _swig_upcall_OnRspRawData(char const *rawData) {
    Directaccess::Directaccess::IMarketEvent::OnRspRawData(rawData);
  }
  virtual void OnRspRawData(char const *rawData);
  void _swig_upcall_OnRspUserLogin(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IMarketEvent::OnRspUserLogin(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspUserLogin(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspTradeDate(CMarketRspTradeDateField *pRspTradeDate,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IMarketEvent::OnRspTradeDate(pRspTradeDate,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspTradeDate(CMarketRspTradeDateField *pRspTradeDate,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspBrokerData(CMarketRspBrokerDataField *pRspBrokerData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IMarketEvent::OnRspBrokerData(pRspBrokerData,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspBrokerData(CMarketRspBrokerDataField *pRspBrokerData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspMarketData(CMarketRspMarketDataField *pRspMarketData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IMarketEvent::OnRspMarketData(pRspMarketData,pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspMarketData(CMarketRspMarketDataField *pRspMarketData,CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnRspUserLogout(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast) {
    Directaccess::Directaccess::IMarketEvent::OnRspUserLogout(pRspInfo,iRequestID,bIsLast);
  }
  virtual void OnRspUserLogout(CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
  void _swig_upcall_OnJsonData(CMarketRspJsonDataField *pRspMarketData) {
    Directaccess::Directaccess::IMarketEvent::OnJsonData(pRspMarketData);
  }
  virtual void OnJsonData(CMarketRspJsonDataField *pRspMarketData);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
